import React from 'react';

export const THEME_TOKENS = {
  colors: {
    white: '#ffffff',
    black: '#000000',
    gray: '#888888',
    lightGray: '#f8f8f8',
    darkGray: '#333333',
    error: '#ff4d4d',
    success: '#00ff00',
    border: '#dddddd',
  },
  spacing: {
    xs: '10px',
    sm: '20px',
    md: '30px',
    lg: '40px',
    xl: '50px',
  },
  typography: {
    fontFamily: 'inherit',
    letterSpacing: '2px',
    letterSpacingLarge: '4px',
    weightBold: 'bold',
    weightBlack: '900',
  },
};

export const layoutStyles: Record<string, React.CSSProperties> = {
  fullPageContainer: {
    height: '100vh',
    width: '100vw',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: THEME_TOKENS.colors.white,
    position: 'fixed',
    top: 0,
    left: 0,
    overflow: 'hidden',
  },
  authCard: {
    width: '450px',
    padding: THEME_TOKENS.spacing.xl,
    border: `1px solid ${THEME_TOKENS.colors.black}`,
    backgroundColor: THEME_TOKENS.colors.white,
    textAlign: 'left',
  },
  dashboardContainer: {
    height: '100vh',
    width: '100vw',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: THEME_TOKENS.colors.white,
    position: 'fixed',
    top: 0,
    left: 0,
  },
};

export const uiElements: Record<string, React.CSSProperties> = {
  descriptionBlock: {
    borderLeft: `4px solid ${THEME_TOKENS.colors.black}`,
    paddingLeft: THEME_TOKENS.spacing.sm,
    marginBottom: THEME_TOKENS.spacing.md,
  },
  descriptionText: {
    fontSize: '11px',
    lineHeight: '1.5',
    margin: 0,
    fontWeight: THEME_TOKENS.typography.weightBold as any,
    textTransform: 'uppercase',
  },
  mainTitle: {
    fontWeight: THEME_TOKENS.typography.weightBlack as any,
    textTransform: 'uppercase',
    letterSpacing: THEME_TOKENS.typography.letterSpacingLarge,
    fontSize: '32px',
    margin: 0,
    lineHeight: '1',
  },
  subtitle: {
    fontSize: '10px',
    color: THEME_TOKENS.colors.gray,
    textTransform: 'uppercase',
    marginTop: '10px',
    marginBottom: THEME_TOKENS.spacing.md,
    letterSpacing: '1px',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: THEME_TOKENS.spacing.sm,
  },
  label: {
    width: '110px',
    fontSize: '10px',
    fontWeight: THEME_TOKENS.typography.weightBold as any,
    textTransform: 'uppercase',
  },
  inputField: {
    flexGrow: 1,
    padding: '8px',
    border: `1px solid ${THEME_TOKENS.colors.black}`,
    borderRadius: 0,
    outline: 'none',
  },
  primaryButton: {
    backgroundColor: THEME_TOKENS.colors.black,
    color: THEME_TOKENS.colors.white,
    padding: '16px',
    border: 'none',
    fontWeight: THEME_TOKENS.typography.weightBold as any,
    textTransform: 'uppercase',
    cursor: 'pointer',
    letterSpacing: '1px',
    transition: 'background-color 0.2s ease',
  },
  secondaryButton: {
    backgroundColor: THEME_TOKENS.colors.white,
    color: THEME_TOKENS.colors.black,
    padding: '16px',
    border: `1px solid ${THEME_TOKENS.colors.black}`,
    fontWeight: THEME_TOKENS.typography.weightBold as any,
    textTransform: 'uppercase',
    cursor: 'pointer',
    textAlign: 'center',
    textDecoration: 'none',
    fontSize: '12px',
  },
  errorMessage: {
    border: `1px solid ${THEME_TOKENS.colors.error}`,
    color: THEME_TOKENS.colors.error,
    padding: THEME_TOKENS.spacing.xs,
    fontSize: '12px',
    marginBottom: THEME_TOKENS.spacing.sm,
    fontWeight: 'bold',
  },
};

export const dashboardStyles: Record<string, React.CSSProperties> = {
  navbar: {
    height: '60px',
    backgroundColor: THEME_TOKENS.colors.black,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: `0 ${THEME_TOKENS.spacing.md}`,
    flexShrink: 0,
  },
  sidebar: {
    width: '120px',
    backgroundColor: THEME_TOKENS.colors.white,
    padding: `20px ${THEME_TOKENS.spacing.md}`,
    borderRight: `1px solid ${THEME_TOKENS.colors.black}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  dashboard: {
    flexGrow: 1,
    padding: THEME_TOKENS.spacing.sm,
    textAlign: 'left',
  },
  badge: {
    fontSize: '9px',
    border: `1px solid ${THEME_TOKENS.colors.black}`,
    padding: '4px 8px',
    fontWeight: 'bold',
    backgroundColor: 'transparent',
    color: THEME_TOKENS.colors.black,
    display: 'inline-block',
  },
};

export const dashboardElements: Record<string, React.CSSProperties> = {
  contentBox: {
    marginTop: THEME_TOKENS.spacing.lg,
    border: `1px solid ${THEME_TOKENS.colors.black}`,
    padding: THEME_TOKENS.spacing.lg,
    minHeight: '300px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: THEME_TOKENS.colors.white,
  },
  placeholderText: {
    fontSize: '11px',
    color: THEME_TOKENS.colors.gray,
    fontWeight: 'bold',
    textAlign: 'center',
    maxWidth: '300px',
    lineHeight: '1.6',
    textTransform: 'uppercase',
  },
  statusMarker: {
    marginTop: 'auto',
    fontSize: '9px',
    fontWeight: 'bold',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    textTransform: 'uppercase',
  },
  statusDot: {
    width: '6px',
    height: '6px',
    backgroundColor: THEME_TOKENS.colors.success,
    borderRadius: 0,
  },
  profileHeader: {
    fontSize: '14px',
    color: THEME_TOKENS.colors.gray,
    textTransform: 'uppercase',
    fontWeight: THEME_TOKENS.typography.weightBlack as any,
    letterSpacing: '1px',
    marginBottom: THEME_TOKENS.spacing.sm,
    textAlign: 'center',
    margin: 0,
    lineHeight: '1',
    // paddingTop: '12px',
  },
  emailDisplay: {
    fontSize: '10px',
    fontWeight: 'bold',
    margin: `0 0 ${THEME_TOKENS.spacing.xs} 0`,
    wordBreak: 'break-all',
    textAlign: 'center',
  },
};
